version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Writing image definition files...
      - printf '{"version":1,"Resources":[{"TargetService":{"Type":"AWS::ECS::Service","Properties":{"TaskDefinition":"<TASK_DEFINITION>","LoadBalancerInfo":{"ContainerName":"ghost-container","ContainerPort":2368}}}}]}' > appspec.yaml
      - printf '{"family":"my_task_family","networkMode":"awsvpc","executionRoleArn":"%s","containerDefinitions":[{"name":"ghost-container","image":"%s.dkr.ecr.%s.amazonaws.com/%s:%s","cpu":1024,"memory":2048,"essential":true,"portMappings":[{"containerPort":2368,"hostPort":2368,"protocol":"tcp"}],"environment":[{"name":"database__client","value":"mysql"},{"name":"database__connection__host","value":"%s"},{"name":"database__connection__user","value":"ghostadmin"},{"name":"database__connection__password","value":"%s"},{"name":"database__connection__database","value":"ghost"},{"name":"url","value":"%s"}],"logConfiguration":{"logDriver":"awslogs","options":{"awslogs-group":"/ecs/ghost","awslogs-region":"%s","awslogs-stream-prefix":"ecs"}}}],"requiresCompatibilities":["FARGATE"],"cpu":"1024","memory":"2048"}' $EXECUTION_ROLE_ARN $AWS_ACCOUNT_ID $AWS_DEFAULT_REGION $IMAGE_REPO_NAME $IMAGE_TAG $DB_HOST $DB_PASSWORD $GHOST_URL $AWS_DEFAULT_REGION > taskdef.json

artifacts:
  files:
    - appspec.yaml
    - taskdef.json
